## 计算两维的xy的平方根得到一维
*  `feature1 =  torch.sqrt( c[:, 0]**2 +  c[:,1]**2) # 两维的平方根`

In [10]:
import torch

c = torch.tensor([[3,4,5],[6,8,4]], dtype=torch.float)
print(c)

tensor([[3., 4., 5.],
        [6., 8., 4.]])


In [11]:
feature1 =  torch.sqrt( c[:, 0]**2 +  c[:,1]**2) # 两维的平方根
# feature1 =  c[:, 0] + c[:,1]
feature1 = feature1.type_as(c).view(-1, 1) # 维度要一致 (3, 1)
print(feature1)
print()

tensor([[ 5.],
        [10.]])



In [12]:
# c[:, 1] = feature1.squeeze()
c[:, 1] = torch.sqrt( c[:, 0]**2 +  c[:,1]**2) # 两维的平方根
print(c[:, 1:])

tensor([[ 5.,  5.],
        [10.,  4.]])


In [13]:
feature = [c]
feature.append(feature1)
print(feature) # 列表
feature = torch.cat(feature, dim=1) #  最后一维合并Combine together feature decorations
print(feature)

[tensor([[ 3.,  5.,  5.],
        [ 6., 10.,  4.]]), tensor([[ 5.],
        [10.]])]
tensor([[ 3.,  5.,  5.,  5.],
        [ 6., 10.,  4., 10.]])


## torch.randint_like(sample_, low=0, high=num_sample)
https://pytorch.org/docs/stable/generated/torch.randint_like.html


In [14]:
# lmv/core/modules/ops/samples.py
import torch
xyz = torch.rand(12,4)
# print(xyz)
num_sample = 6
valid_sample_ids = torch.arange(12)
print(valid_sample_ids)
# 只要6个
sample_ = xyz.new_zeros(num_sample).long() # 方便的复制原来tensor的所有类型，比如数据类型和数据所在设备等等
print("sample_: ", sample_)
extra_idx = torch.randint_like(sample_, low=0, high=num_sample) # input填充了在low（包括）和 high（不包括）之间均匀生成的随机整数。====================
print("extra_idx: ", extra_idx)
sample_ids = valid_sample_ids[extra_idx]
print(sample_ids)
print(xyz[sample_ids,:])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
sample_:  tensor([0, 0, 0, 0, 0, 0])
extra_idx:  tensor([1, 0, 4, 2, 4, 0])
tensor([1, 0, 4, 2, 4, 0])
tensor([[0.7889, 0.4091, 0.5140, 0.4285],
        [0.3778, 0.9903, 0.2365, 0.2286],
        [0.9092, 0.6876, 0.2738, 0.4460],
        [0.4123, 0.0090, 0.7043, 0.3341],
        [0.9092, 0.6876, 0.2738, 0.4460],
        [0.3778, 0.9903, 0.2365, 0.2286]])
