## feature1 = feature[:,0].type_as(feature).view(-1, 1) # ！！！！注意列表中的tensor的维度必须一致

In [11]:
import torch

x = torch.ones(1,1,2,4)
x1 = x*2
blocks = []
blocks.append(x)
blocks.append(x1)

ups = [block for i, block in enumerate(blocks)]
print('x的shape', x)
print(x1)
print(ups)
out = (torch.cat(ups,  dim=1)) # 在第一维合并
print("out.shape", out.shape)
print(out)


x的shape tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
tensor([[[[2., 2., 2., 2.],
          [2., 2., 2., 2.]]]])
[tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]]), tensor([[[[2., 2., 2., 2.],
          [2., 2., 2., 2.]]]])]
out.shape torch.Size([1, 2, 2, 4])
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[2., 2., 2., 2.],
          [2., 2., 2., 2.]]]])


In [10]:
import torch

feature = torch.tensor([[3,4,5],[6,8,4]], dtype=torch.float)
print(feature)
list1 = [feature]
feature1 = feature[:,0].type_as(feature).view(-1, 1) # ！！！！注意列表中的tensor的维度必须一致
list1.append(feature1)
print(list1)
print(torch.cat(list1, dim=-1))


tensor([[3., 4., 5.],
        [6., 8., 4.]])
[tensor([[3., 4., 5.],
        [6., 8., 4.]]), tensor([[3.],
        [6.]])]
tensor([[3., 4., 5., 3.],
        [6., 8., 4., 6.]])
