# torch.sum()
https://blog.csdn.net/qq_39463274/article/details/105145029

In [5]:
import torch
out = torch.arange(6).reshape(2,3)
print(out)
print(torch.sum(out,dim=0), torch.sum(out,dim=1)) # 所在元素内的维度处理

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([3, 5, 7]) tensor([ 3, 12])


In [2]:
import torch

x = torch.ones(1,1,2,4)
x1 = x*2
blocks = []
blocks.append(x)
blocks.append(x1)

ups = [block for i, block in enumerate(blocks)]
print(ups)
print(x)
print(x1)
print("直接相加：", x+x1)

[tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]]), tensor([[[[2., 2., 2., 2.],
          [2., 2., 2., 2.]]]])]
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
tensor([[[[2., 2., 2., 2.],
          [2., 2., 2., 2.]]]])
直接相加： tensor([[[[3., 3., 3., 3.],
          [3., 3., 3., 3.]]]])


In [24]:
x =1
y =2
mylist = [x, y]

print(mylist)

[1, 2]
