# 
https://www.cnblogs.com/wanghui-garcia/p/11266298.html

https://zhuanlan.zhihu.com/p/260162240


```
torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)
```
input：输入tensor
p (int, float, inf, -inf, 'fro', 'nuc', optional)：范数计算中的幂指数值。默认为'fro'


dim (int，2-tuple，2-list， optional): 指定计算的维度。如果是一个整数值，向量范数将被计算；如果是一个大小为2的元组，矩阵范数将被计算；如果为None，当输入tensor只有两维时矩阵计算矩阵范数；当输入只有一维时则计算向量范数。如果输入tensor超过2维，向量范数将被应用在最后一维
keepdim（bool，optional）：指明输出tensor的维度dim是否保留。如果dim=None或out=None,则忽略该参数。默认值为False，不保留
out（Tensor, optional）:tensor的输出。如果dim=None或out=None,则忽略该参数。
dtype（torch.dtype，optional）：指定返回tensor的期望数据类型。如果指定了该参数，在执行该操作时输入tensor将被转换成 :attr:’dtype’


In [5]:
import torch

c = torch.tensor([[1,2,3],[-1,1,4]], dtype=torch.float)
print(c)
print(torch.norm(c, dim=0))

tensor([[ 1.,  2.,  3.],
        [-1.,  1.,  4.]])
tensor([1.4142, 2.2361, 5.0000])


In [12]:
torch.norm(c, dim=0)# 指定dim = 0，因为c的size() = (2,3),所以会去掉其dim=0，得到size()=(3)的结果，所以是纵向求值，计算Frobenius范数
# torch.norm(c, dim=0).size()  # torch.Size([3])

tensor([1.4142, 2.2361, 5.0000])

In [3]:
torch.norm(c, dim=1)

tensor([3.7417, 4.2426])

In [4]:
torch.norm(c, p=1, dim=1) # p=1, dim=1 ： 即是表示去掉维度1，使用1-范数，得到size()=(2)的结果。所以横向计算各个元素绝对值的和，为（[6,6]）

tensor([6., 6.])