# 数据处理
TODO

Tips:
* 有时候tensor需要转到numpy进行处理

https://www.yuque.com/huangzhongqing/pytorch/gck7a0#C4vQj

In [39]:
import torch
import numpy as np
a = torch.tensor([
    [1,2,3,],
    [4,5,6]
], dtype=torch.float32)
print(a)
print(np.arange(12))  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

x=torch.arange(12).view(3,4)
print(x)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
[ 0  1  2  3  4  5  6  7  8  9 10 11]
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## np和tensor的互换
1. x.numpy()
2. torch.from_numpy(x)

In [11]:
import torch
x = torch.rand(2,2)
x1 = x.numpy() # torch转换到numpy
x2 = torch.from_numpy(x1) #numpy转换torch   torch.from_numpy(ndarray)--->Tensor

### 

## 维度交换 transpose()和permute()
1. 交换维度 分别时transpose()和permute()
2. 交换维度内的列

In [17]:
# 该函数可以交换tensor的任意两个维度，即一次只能交换两个维度
import torch
x = torch.randn(8, 3, 5, 4)
y = x.transpose(1,2)  # 交换第二与第三维度
print(y.shape)



# 类别numpy的transpose
## 应用 xyz变换
points = torch.randn(1, 3, 256).cuda()
final_xyz = points.detach().cpu().numpy() #  最后采样点 256
final_xyz = np.transpose(final_xyz, (0,2,1)) # 交换维度
print(final_xyz.shape)

torch.Size([8, 5, 3, 4])
(1, 256, 3)


In [8]:
# 该函数可以随意交换任意维度，并且可以重新排列整合维度

z1 = x.permute(0,2,1,3)  # 交换第二与第三维度
print(z1.shape)
z2 = x.permute(3,0,2,1)  # 对原维度重新排列整合
print(z2.shape)

torch.Size([8, 5, 3, 4])
torch.Size([4, 8, 5, 3])


In [18]:
# 交换维度内的列
# torch.ones(4,24513,4) torch.zeros(4,134343,4)
gt_bboxes = torch.randn(6,8) #  (label,xyzlwl.r)# (1,6,8)# 
gt_bboxes = gt_bboxes[:,[7,0,1,2,3,4,5,6]] # 交换列
# print(gt_bboxes)

## 拼接torch.cat(=np.concatenate) &torch.stack(=np.stack())
torch.cat &torch.stack(sequence, dim=0, out=None)，
#注: .cat 和 .stack的区别在于 cat会增加现有维度的值(行列数量),可以理解为续接，stack会新加增加一个维度

* torch.cat(seq,dim=0,out=None) # 沿着dim连接seq中的tensor, 所有的tensor必须有相同的size或为empty， 其相反的操作为 torch.split() 和torch.chunk()
* torch.stack(seq, dim=0, out=None) #同上

>>> a=torch.Tensor([1,2,3])
>>> torch.stack((a,a)).size()
torch.size(2,3)
>>> torch.cat((a,a)).size()
torch.size(6)

In [31]:
# result = torch.cat([pred_bbox[0,:,:], pred_label[0,:,:]], dim=1) 
pred_bbox = torch.randn(1, 32, 7)
pred_label = torch.ones(1,32,1) #把0去掉或者reshape[0,:,:]
result = torch.cat([pred_bbox[0,:,:], pred_label[0,:,:]], dim=1) # 
print(result.shape)
print(result[:5,:])

torch.Size([32, 8])
tensor([[-0.2273, -0.4295,  1.4026, -2.3180,  1.7877,  0.9202,  0.1598,  1.0000],
        [-1.7302,  0.2141, -0.6040,  0.4102,  0.8396,  0.4340,  1.3516,  1.0000],
        [ 1.0719, -0.3730,  0.7672,  0.4611, -0.4092, -0.2790, -0.8011,  1.0000],
        [ 0.3402, -0.3748, -1.1944,  1.8757, -0.5044, -0.5347, -0.1162,  1.0000],
        [-0.6060,  1.5955,  0.1573,  0.1331,  0.3430,  0.0413,  1.4608,  1.0000]])


In [4]:
import torch
a=torch.tensor([[1,2,3],
                [4,5,6]])  # 2x3
b=torch.tensor([[10,20,30],
                [40,50,60]])
c=torch.tensor([[100,200,300],
                [400,500,600]])
print(torch.stack([a,b,c],dim=0)) # 0维
print(torch.stack([a,b,c],dim=1)) # 
print(torch.stack([a,b,c],dim=2)) # 将每个tensor的第i行转置后按列连接组成一个新的2维tensor，再将这些新tesnor按照dim=0的方式连接
print(torch.stack((a,b,c),dim=0).size())
print(torch.stack([a,b,c],dim=1).size())
print(torch.stack([a,b,c],dim=2).size())
print(torch.cat((a,b,c), dim=-1))


# dim=0时，将tensor在一维上连接，简单来说就是，就是将tensor1，tensor2…tensor n,连接为【tensor1，tensor2… tensor n】（就是在这里产生了扩维）
# dim=1时，将每个tensor的第i行按行连接组成一个新的2维tensor，再将这些新tensor按照dim=0的方式连接。
# dim=2时，将每个tensor的第i行转置后按列连接组成一个新的2维tensor，再将这些新tesnor按照dim=0的方式连接
# 原文链接：https://blog.csdn.net/realcoder/article/details/105846408

tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[ 10,  20,  30],
         [ 40,  50,  60]],

        [[100, 200, 300],
         [400, 500, 600]]])
tensor([[[  1,   2,   3],
         [ 10,  20,  30],
         [100, 200, 300]],

        [[  4,   5,   6],
         [ 40,  50,  60],
         [400, 500, 600]]])
tensor([[[  1,  10, 100],
         [  2,  20, 200],
         [  3,  30, 300]],

        [[  4,  40, 400],
         [  5,  50, 500],
         [  6,  60, 600]]])
torch.Size([3, 2, 3])
torch.Size([2, 3, 3])
torch.Size([2, 3, 3])
tensor([[  1,   2,   3,  10,  20,  30, 100, 200, 300],
        [  4,   5,   6,  40,  50,  60, 400, 500, 600]])


## 维度增减unsqueeze是squeeze

## 1个维度torch.squeeze(inout,dim=None,out=None) &torch.unsqueeze() 
* torch.squeeze() 对于tensor变量进行维度压缩，去除维数为1的的维度
* unsqueeze是squeeze()的反向操作，增加一个维度，该维度维数为1，可以指定添加的维度。

In [15]:
import torch
out = torch.arange(12).reshape(1,3,4)
print(out.shape)
print(torch.squeeze(out).shape)
print(torch.unsqueeze(out, dim=0).shape) # 在0维之前插入这一维

torch.Size([1, 3, 4])
torch.Size([3, 4])
torch.Size([1, 1, 3, 4])


## 数据筛选

### 筛选满足条件的行列

In [41]:
# lmv/core/trainers.py
# 筛选第一列不等于0
gt_bboxes =torch.arange(12).view(3,4)
print(gt_bboxes,gt_bboxes[:,0] != 0) # tensor([False,  True,  True]) 每行第1列（label）不等于0
gt_bboxes = gt_bboxes[gt_bboxes[:,0] != 0, :] # 第1列（label）不等于0
print(gt_bboxes)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) tensor([False,  True,  True])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [49]:
x = torch.arange(5).reshape(1,5)
print(x,x.shape)
print(x>2) # tensor([[False, False, False,  True,  True]])
print(x[x>2])

tensor([[0, 1, 2, 3, 4]]) torch.Size([1, 5])
tensor([[False, False, False,  True,  True]])
tensor([3, 4])


### 索引（index_select()。 masked_select()）
https://blog.csdn.net/Env1sage/article/details/124719553?

##  torch.gather/scatter_ 聚集/分散操作

https://www.yuque.com/huangzhongqing/pytorch/gck7a0#BziNU

一般scatter用于生成onehot向量。https://blog.csdn.net/qq_39004117/article/details/95665418

`torch.Tensor.scatter_(dim, index, src) → Tensor`

字面意思：对一个 torch.Tensor 进行操作，dim，index，src三个为输入的参数。

* dim 就是在哪个维度进行操作，注意，dim 的不同，在其他条件相同的条件下得到的output 也不同。
* index 是输入的索引。
* src 就是输入的向量，也就是 input。
相关：/home/chongqinghuang/code/lmv/core/models/utils.py

In [9]:
import torch
 
# input = torch.ones(2, 4)
input = 1
print(input)
output = torch.zeros(3, 5)
print(output)
index = torch.tensor([[1], [2], [3]]) # 在不同的下标位置赋值1
output = output.scatter(1, index, input)
print(output)

1
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])
