## torch.max() torch.sum() torch.norm()

## torch.max() min()
* 方法1：得到某一维度
* 方法2：最大最小值是数组形式!!

In [ ]:
import torch

x = torch.rand(4,4)
print('x:\n',x)
#  tensor([[0.3736, 0.4062, 0.4501, 0.4946],
#         [0.9313, 0.8332, 0.9322, 0.0988],
#         [0.3764, 0.3940, 0.8055, 0.2494],
#         [0.2100, 0.3560, 0.7563, 0.5658]])
print('torch.max(x,1):\n',torch.max(x,1))
print('torch.max(x,0):\n',torch.max(x,0))
print('torch.max(x,1)[0]:\n',torch.max(x,1)[0])
print('torch.max(x,1)[1]:\n',torch.max(x,1)[1])
print('torch.max(x,1)[1].data:\n',torch.max(x,1)[1].data)
print('torch.max(x,1)[1].data.numpy():\n',torch.max(x,1)[1].data.numpy())
print('torch.max(x,1)[1].data.numpy().squeeze():\n',torch.max(x,1)[1].data.numpy().squeeze())
print('torch.max(x,1)[0].data:\n',torch.max(x,1)[0].data)
print('torch.max(x,1)[0].data.numpy():\n',torch.max(x,1)[0].data.numpy())
print('torch.max(x,1)[0].data.numpy().squeeze():\n',torch.max(x,1)[0].data.numpy().squeeze())

In [4]:
## 方法2：最大最小值是数组形式
vote_offsets = torch.tensor([[[-5.0, -1.4586e+00,  9.5761e-02, -6.3620e-01, -6.1594e-01],
                    [5., -7.6953e-01,  2.3583e-01, -1.3664e+00,  3.7694e-01],
                    [-2., -2.0000e+00,  4.9579e-01, -7.2171e-01, -6.7554e-01],]]).cuda() # # torch.Size([1, 3, 5])
vote_translation_range = torch.tensor([[[3.],
                                        [3.],
                                        [2.]]]).cuda() # torch.Size([1, 3, 1])
vote_offsets = torch.max(vote_offsets, -vote_translation_range) # 最小-vote_translation_range
print(vote_offsets)
vote_offsets = torch.min(vote_offsets, vote_translation_range) # 最大 vote_translation_range
print(vote_offsets)

tensor([[[-3.0000, -1.4586,  0.0958, -0.6362, -0.6159],
         [ 5.0000, -0.7695,  0.2358, -1.3664,  0.3769],
         [-2.0000, -2.0000,  0.4958, -0.7217, -0.6755]]], device='cuda:0')
tensor([[[-3.0000, -1.4586,  0.0958, -0.6362, -0.6159],
         [ 3.0000, -0.7695,  0.2358, -1.3664,  0.3769],
         [-2.0000, -2.0000,  0.4958, -0.7217, -0.6755]]], device='cuda:0')
