参考：
* 官网中文：https://pytorch.apachecn.org/docs/1.4/blitz/tensor_tutorial.html
* 深度学习之Pytorch基础教程！
： https://mp.weixin.qq.com/s/kDGHQQ_wRQXds34HHCQNOQ

PyTorch是一个基于python的科学计算包，主要针对两类人群：

* 作为NumPy的替代品，可以利用GPU的性能进行计算
* 作为一个高灵活性、速度快的深度学习平台


### 目录
* 1 张量
* 2 运算
    * 算数运算
    * 索引
    * 改变形状
* 3 广播机制
* 4 Tensor和Numpy相互转化
* 5  GPU运算

## 张量
Tensor(张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算。

这些创建方法都可以在创建的时候**指定数据类型dtype和存放device(cpu/gpu)。**



![](https://mmbiz.qpic.cn/mmbiz_png/vI9nYe94fsFfaUzHsEvJhbPArzshFk0NqR3RY4k3mwKZHCVPwkJTicyUhu53eKDqOuKt45jhMqaK7lEdiaXYDSvA/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

In [3]:
from __future__ import print_function
import torch

In [4]:
# 创建未初始化的Tensor
x = torch.empty(5,3)
print(x)

tensor([[4.7428e+30, 2.5062e-12, 1.4586e-19],
        [8.1546e-33, 1.3563e-19, 1.6114e-19],
        [1.8042e+28, 1.7899e+19, 1.6457e+19],
        [1.4585e-19, 6.7421e+22, 5.0761e+31],
        [1.3556e-19, 7.2053e+22, 4.7428e+30]])


In [5]:
# 创造随机初始化的Tensor  rand
x = torch.rand(5,3)
print(x)

tensor([[0.7685, 0.0247, 0.4373],
        [0.8077, 0.9733, 0.8917],
        [0.5988, 0.3023, 0.0215],
        [0.1832, 0.5932, 0.4136],
        [0.7592, 0.6733, 0.5404]])


In [6]:
# 全为0的Tensor  zeros
x = torch.zeros(2,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
# 根据数据创建Tensor  tensor
x = torch.tensor([2,3,4])
print(x)

tensor([2, 3, 4])


In [8]:

# 修改原Tensor为全1的Tensor
x = x.new_ones(5,3,dtype=torch.float64)
print(x)

# 修改数据类型  rand_like   返回与输入相同大小的张量，该张量由区间[0,1)上均匀分布的随机数填充
x = torch.rand_like(x,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.1745, 0.3031, 0.4357],
        [0.0771, 0.0306, 0.5096],
        [0.5548, 0.6502, 0.4673],
        [0.0561, 0.3961, 0.8094],
        [0.1659, 0.1197, 0.2819]], dtype=torch.float64)


In [9]:
# 获取形状
print(x.size())
print(x.shape)

# 输出torch.Size本质上还是tuple，所以支持tuple的一切操作。

torch.Size([5, 3])
torch.Size([5, 3])


## 运算

### 1 算数操作
有三种加法运算
* x+y
* torch.add(x, y, , out=result)
* y.add_(x)    print(y)  # add x to y

> 注意：
任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x

In [10]:
y = torch.ones(5,3)
print(x+y)

result = torch.rand(5,3)  # pytorch  NameError: name  result  is not defined
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)


tensor([[1.1745, 1.3031, 1.4357],
        [1.0771, 1.0306, 1.5096],
        [1.5548, 1.6502, 1.4673],
        [1.0561, 1.3961, 1.8094],
        [1.1659, 1.1197, 1.2819]], dtype=torch.float64)
tensor([[1.1745, 1.3031, 1.4357],
        [1.0771, 1.0306, 1.5096],
        [1.5548, 1.6502, 1.4673],
        [1.0561, 1.3961, 1.8094],
        [1.1659, 1.1197, 1.2819]])
tensor([[1.1745, 1.3031, 1.4357],
        [1.0771, 1.0306, 1.5096],
        [1.5548, 1.6502, 1.4673],
        [1.0561, 1.3961, 1.8094],
        [1.1659, 1.1197, 1.2819]])


### 2 索引
* 需要注意的是：索引出来的结果与原数据共享内存，也即修改⼀个，另⼀个会跟着修改。

In [11]:
y = x[0, :]
y+=1
print(y)
print(x[0,:])

tensor([1.1745, 1.3031, 1.4357], dtype=torch.float64)
tensor([1.1745, 1.3031, 1.4357], dtype=torch.float64)


### 3 改变形状  view()
* 类似reshape,但reshape不共享内存
* -1所指的维度可以根据其他维度的值推出来
* 注意 view() 返回的新tensor与源tensor共享内存（其实是同⼀个tensor），也即更改其中的⼀个，另 外⼀个也会跟着改变。(顾名思义，view仅是改变了对这个张量的观察角度)

In [12]:
y = x.view(15)
z = x.view(-1, 5)
print(x.shape, y.shape, z.shape)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [13]:

x += 1
print(x)  # 共享内存
print(y)

tensor([[2.1745, 2.3031, 2.4357],
        [1.0771, 1.0306, 1.5096],
        [1.5548, 1.6502, 1.4673],
        [1.0561, 1.3961, 1.8094],
        [1.1659, 1.1197, 1.2819]], dtype=torch.float64)
tensor([2.1745, 2.3031, 2.4357, 1.0771, 1.0306, 1.5096, 1.5548, 1.6502, 1.4673,
        1.0561, 1.3961, 1.8094, 1.1659, 1.1197, 1.2819], dtype=torch.float64)


#### 如果我们想返回⼀个真正新的副本（即不共享内存）该怎么办呢？Pytorch还提供了⼀ 个 reshape() 可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先 ⽤ clone 创造一个副本然后再使⽤ view 。

In [14]:

x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[1.1745, 1.3031, 1.4357],
        [0.0771, 0.0306, 0.5096],
        [0.5548, 0.6502, 0.4673],
        [0.0561, 0.3961, 0.8094],
        [0.1659, 0.1197, 0.2819]], dtype=torch.float64)
tensor([2.1745, 2.3031, 2.4357, 1.0771, 1.0306, 1.5096, 1.5548, 1.6502, 1.4673,
        1.0561, 1.3961, 1.8094, 1.1659, 1.1197, 1.2819], dtype=torch.float64)


#### 另外⼀个常用的函数就是 item() ,如果是仅包含一个元素的tensor， 它可以将⼀个标量 Tensor 转换成⼀个Python数值

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.0538])
-0.05384066700935364


### 后续阅读：

超过100种tensor的运算操作，包括转置，索引，切片，数学运算， 线性代数，随机数等，具体访问这里
https://pytorch.org/docs/stable/torch.html

## 3 广播机制
当对两个形状不同的 Tensor 按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个 Tensor 形状相同后再按元素运算。例如：

In [23]:
x = torch.arange(1,3).view(1, 2)  # torch.arange(start=1, end=6)的结果并不包含end。torch.range(start=1, end=6) 的结果是会包含end的
print(x)
y = torch.arange(1,4).view(3, 1)
print(y)
print(x+y)

tensor([1, 2])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [25]:
    import torch
 
    y = torch.range(1, 6)
 
    print(y)
    print(y.dtype)
 
    z = torch.arange(0, 6)
    print(z)
    print(z.dtype)

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
tensor([0, 1, 2, 3, 4, 5])
torch.int64


## 4 Tensor和Numpy相互转化

我们很容易⽤** numpy() 和 from_numpy() **将 Tensor 和NumPy中的数组相互转换。

* 但是需要注意的⼀点是：这两个函数所产生的的 Tensor 和NumPy中的数组共享相同的内存（所以他们之间的转换很快），改变其中⼀个时另⼀个也会改变！！！

In [26]:

a = torch.ones(5)
b = a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [27]:

a += 1
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [28]:

b += 1
print(a,b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


#### 使⽤ from_numpy() 将NumPy数组转换成 Tensor :



In [29]:

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## 5  GPU运算

张量可以使用.to方法移动到任何设备(device）上：



In [30]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)
