## add_pr_curve

https://www.yuque.com/huangzhongqing/hre6tf/bz88ccq3px8bax5z#HNQA7


In [8]:

from torch.utils.tensorboard import SummaryWriter

# 按住ctrl. 鼠标点击查看源码
writer = SummaryWriter("../logs/tb_add_pr_curve")

In [18]:
import numpy as np
def add_pr_curve(writer):
    from sklearn.linear_model import LogisticRegression
    from sklearn.preprocessing import label_binarize
    def get_dataset():
        from sklearn.datasets import load_iris
        from sklearn.model_selection import train_test_split
        x, y = load_iris(return_X_y=True)
        random_state = np.random.RandomState(2020)
        n_samples, n_features = x.shape
        # 为数据增加噪音维度以便更好观察pr曲线
        x = np.concatenate([x, random_state.randn(n_samples, 100 * n_features)], axis=1)
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5,
        random_state=random_state)
        return x_train, x_test, y_train, y_test

    x_train, x_test, y_train, y_test = get_dataset()
    model = LogisticRegression(multi_class="ovr")
    model.fit(x_train, y_train)
    # result
    # 预测概率(每个label的概率)
    y_scores = model.predict_proba(x_test)  # shape: (n,3) 每个label都有一个概率！！！！！！！ eg.[0.014668474723677391, 0.6229959204398572, 0.3623356048364655]
    # GT label
    b_y = label_binarize(y_test, classes=[0, 1, 2])  # shape: (n,3)  GT label生成one-hot(0/1) 比如2,就变成[0,0,1]
    print(f"y_scores: {y_scores}")
    print(f"b_y: {b_y}")
    for i in range(3):
        writer.add_pr_curve(f"pr_curve/label_{i}", b_y[:, i], y_scores[:, i], global_step=1)

# 调用
add_pr_curve(writer)

y_scores: [[1.46684747e-02 6.22995920e-01 3.62335605e-01]
 [2.11566844e-02 3.62929510e-01 6.15913805e-01]
 [3.76210935e-01 6.12273928e-01 1.15151370e-02]
 [5.25716121e-01 4.57438373e-01 1.68455060e-02]
 [1.48374664e-01 8.39774630e-01 1.18507062e-02]
 [7.32693248e-02 8.18027639e-01 1.08703036e-01]
 [3.08313182e-02 9.96167591e-02 8.69551923e-01]
 [9.15944837e-01 6.80317436e-02 1.60234194e-02]
 [2.74011963e-01 3.62553385e-01 3.63434652e-01]
 [1.39120035e-02 6.27509141e-02 9.23337082e-01]
 [1.93352893e-01 7.90867508e-01 1.57795993e-02]
 [9.38232716e-01 3.26648980e-02 2.91023858e-02]
 [4.47629677e-01 4.62726211e-01 8.96441113e-02]
 [9.59095960e-01 3.66114801e-02 4.29256035e-03]
 [1.35756491e-02 2.01843732e-01 7.84580619e-01]
 [2.32990527e-02 7.00585226e-01 2.76115722e-01]
 [1.70733178e-01 6.35614697e-01 1.93652125e-01]
 [3.12579527e-02 1.45342558e-02 9.54207791e-01]
 [1.21827522e-01 1.73942022e-01 7.04230457e-01]
 [2.17253674e-03 1.63999359e-01 8.33828104e-01]
 [9.81592318e-01 8.79627695e-0

y_scores: [[1.46684747e-02 6.22995920e-01 3.62335605e-01]
 [2.11566844e-02 3.62929510e-01 6.15913805e-01]
 [3.76210935e-01 6.12273928e-01 1.15151370e-02]
 [5.25716121e-01 4.57438373e-01 1.68455060e-02]
 [1.48374664e-01 8.39774630e-01 1.18507062e-02]
 [7.32693248e-02 8.18027639e-01 1.08703036e-01]
 [3.08313182e-02 9.96167591e-02 8.69551923e-01]
 [9.15944837e-01 6.80317436e-02 1.60234194e-02]
 [2.74011963e-01 3.62553385e-01 3.63434652e-01]
 [1.39120035e-02 6.27509141e-02 9.23337082e-01]
 [1.93352893e-01 7.90867508e-01 1.57795993e-02]
 [9.38232716e-01 3.26648980e-02 2.91023858e-02]
 [4.47629677e-01 4.62726211e-01 8.96441113e-02]
 [9.59095960e-01 3.66114801e-02 4.29256035e-03]
 [1.35756491e-02 2.01843732e-01 7.84580619e-01]
 [2.32990527e-02 7.00585226e-01 2.76115722e-01]
 [1.70733178e-01 6.35614697e-01 1.93652125e-01]
 [3.12579527e-02 1.45342558e-02 9.54207791e-01]
 [1.21827522e-01 1.73942022e-01 7.04230457e-01]
 [2.17253674e-03 1.63999359e-01 8.33828104e-01]
 [9.81592318e-01 8.79627695e-0